name: OSV-Scanner PR Scan

on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

permissions:
  actions: read
  security-events: write
  contents: read
  pull-requests: write  # Needed to post comments

jobs:
  osv-scan-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        id: osv
        uses: google/osv-scanner-action@v2.2.3
        with:
          scan-args: --json .
        continue-on-error: true

      - name: Save OSV results
        run: |
          echo '${{ steps.osv.outputs.json-results }}' > osv-results.json

      - name: Format OSV results for comment
        id: format
        run: |
          if [ -s osv-results.json ]; then
            VULNS=$(jq -r '.results | map(select(.vulnerabilities != null and .vulnerabilities | length > 0)) | length' osv-results.json)
            if [ "$VULNS" -gt 0 ]; then
              SUMMARY=":warning: **OSV Scanner found $VULNS vulnerable package(s).**"
              DETAILS="\`\`\`json
$(cat osv-results.json | jq '.results | map(select(.vulnerabilities != null and .vulnerabilities | length > 0))')
\`\`\`"
            else
              SUMMARY=":white_check_mark: **OSV Scanner found no vulnerable packages.**"
              DETAILS=""
            fi
          else
            SUMMARY=":grey_question: **OSV Scanner did not produce a result file.**"
            DETAILS=""
          fi
          {
            echo "$SUMMARY"
            echo ""
            echo "$DETAILS"
          } > osv-comment.md

      - name: Comment on PR with results
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: osv-comment.md
